{
 "title": "Kubernetes Events Dashboard",
 "description": "Universal and flexible kubernetes events dashboard for logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Kubernetes Events Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (type) (count_over_time({container=\"event-exporter\"}| json |  __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Warning Enents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"event-exporter\"}| json | type = \"Warning\" | __error__=\"\" [$__interval]))",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Image Pull Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"event-exporter\"}|= \"Error: ImagePullBackOff\" | json | reason = \"Failed\"  | line_format \"{{ .message }}\"| __error__=\"\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Container Crashed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"event-exporter\"}| json | reason = \"BackOff\"| __error__=\"\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Container OOM Killed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"event-exporter\"} | json | reason = \"OOMKilling\"| __error__=\"\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Liveness Check Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"event-exporter\"} |= \"failed liveness probe\"| json | reason = \"Killing\"| __error__=\"\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Schedule Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"event-exporter\"}| json | reason = \"FailedScheduling\"| __error__=\"\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Pod Evicted",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"event-exporter\"}|= \"Marking for deletion Pod\"| json | reason = \"TaintManagerEviction\"| __error__=\"\"[$__interval]))"
    }
   ]
  },
  {
   "title": "TOP 10  Kubernetes Events",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "topk(10,sum by (reason) (count_over_time({container=\"event-exporter\"}| json | __error__=\"\"[$__interval])))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Kubernetes Events Source",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"event-exporter\"}| json| __error__=\"\"[$__interval])) by (source_component)",
     "legendFormat": "{{source_component}}"
    }
   ]
  },
  {
   "title": "Kubernetes  Events Type",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"event-exporter\"}| json| __error__=\"\"[$__interval])) by (involvedObject_kind)",
     "legendFormat": "{{involvedObject_kind}}"
    }
   ]
  },
  {
   "title": "Kubernetes Live Events",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{container=\"event-exporter\"}"
    }
   ]
  }
 ]
}