version: 0.2

phases:
  install:
    commands:
      - pip3 uninstall awscli -y
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
      - aws --version

  pre_build:
    commands:
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x kubectl && mv kubectl /usr/local/bin/
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

  build:
    commands:
      - sed -i -e "s/LOKI_STORE_REGION/$LOKI_STORE_REGION/g" -e "s/LOKI_BUCKET_NAME/$LOKI_BUCKET_NAME/g" loki/yaml/configmap-loki.yaml
      - sed -i "s/LOKI_SA_ROLE_ARN/$LOKI_SA_ROLE_ARN/g" loki/yaml/serviceaccount-loki.yaml
      - cd loki/yaml && kubectl apply -f .
      - kubectl -n loki get all
      
  post_build:
    commands:
      - echo "===============Grafana Login Info==============="
      - echo "Grafana Login Username:"`kubectl -n loki get secrets loki-grafana -o jsonpath={.data.admin-user} |base64 -d`
      - echo "Grafana Login Password:"`kubectl -n loki get secrets loki-grafana -o jsonpath={.data.admin-password} |base64 -d`
      - echo "Grafana Login Address:http://"`kubectl get node -o wide |awk '{print $7}' |awk 'NR==2'`':'`kubectl -n loki get svc loki-grafana -o jsonpath={.spec.ports[0].nodePort}`
      - echo "===============Grafana Login Info==============="