apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: LOKI_SA_ROLE_ARN
  labels:
    app: loki
    chart: loki-2.9.1
    heritage: Helm
    release: loki
  name: loki
  namespace: loki
automountServiceAccountToken: true