version: 0.2

phases:
  install:
    commands:
      - aws eks update-kubeconfig --region $REGION --name $EKS_CLUSTER_NAME
      - wget https://github.com/weaveworks/eksctl/releases/download/v0.92.0/eksctl_Linux_amd64.tar.gz
      - tar zxf eksctl_Linux_amd64.tar.gz
      - chmod +x eksctl && mv eksctl /usr/local/bin/
      - eksctl version
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x kubectl && mv kubectl /usr/local/bin/
      - kubectl version
      - kubectl create ns loki
      - git clone https://$SOURCE_CODE_VENDOR.com/HeyJiqing/AWSCodeBuild.git
      - cd AWSCodeBuild

  pre_build:
    commands:
      - eksctl utils associate-iam-oidc-provider --region $REGION --cluster $EKS_CLUSTER_NAME --approve
      - eksctl create iamserviceaccount --region $REGION --cluster $EKS_CLUSTER_NAME --namespace loki --name loki --attach-policy-arn $SAPOLICY --override-existing-serviceaccounts --approve
      - sed -i -e "s/REGION/$REGION/g" -e "s/LOKI_BUCKET_NAME/$LOKI_BUCKET_NAME/g" -e "s/LOKI_DDB_TABLE_NAME/$LOKI_DDB_TABLE_NAME/g" yaml/loki-all.yaml
  
  build:
    commands:
      - kubectl apply -f yaml/loki-all.yaml
      - kubectl -n loki get all

  post_build:
    commands:
      - echo && echo "=========================Grafana Login Info=========================" && echo "Grafana Login Username:"`kubectl -n loki get secrets loki-grafana -o jsonpath={.data.admin-user} |base64 -d` && echo "Grafana Login Password:"`kubectl -n loki get secrets loki-grafana -o jsonpath={.data.admin-password} |base64 -d` && echo "Grafana Login Address:http://"`kubectl get node -o wide |awk '{print $7}' |awk 'NR==2'`':'`kubectl -n loki get svc loki-grafana -o jsonpath={.spec.ports[0].nodePort}` && echo "=========================Grafana Login Info========================="
      - echo && echo "=========================Delete Loki Steps=========================" && echo "1) Delete CloudFormation Stack [eksctl-eks-loki-addon-iamserviceaccount-loki-loki]" && echo "2) Delete CloudFormation Stack [Loki]" && echo "3) Delete Kubernetes NS With [kubectl delete ns loki]" && echo "4) Delete Kubernetes Resources With [kubectl delete -f https://gitee.com/HeyJiqing/AWSCodeBuild/raw/master/yaml/loki-all.yaml]" && echo "=========================Delete Loki Steps========================="